// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYV7xRQf2yDNTsiDWv-mui7TARnDZSC4A',
    appId: '1:91192132276:web:fa22c5faa7289c8a678de1',
    messagingSenderId: '91192132276',
    projectId: 'nlp-chat-app-1fd03',
    authDomain: 'nlp-chat-app-1fd03.firebaseapp.com',
    storageBucket: 'nlp-chat-app-1fd03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJkdb9hAH2fcBlKTLfCSaV69P_69hdIg',
    appId: '1:91192132276:android:50e40abe6dbf0cd3678de1',
    messagingSenderId: '91192132276',
    projectId: 'nlp-chat-app-1fd03',
    storageBucket: 'nlp-chat-app-1fd03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAuMvDk3jf0s6wIwxuw7hmDz_wuzRs0dQ',
    appId: '1:91192132276:ios:b578c450700564d4678de1',
    messagingSenderId: '91192132276',
    projectId: 'nlp-chat-app-1fd03',
    storageBucket: 'nlp-chat-app-1fd03.appspot.com',
    iosBundleId: 'com.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAuMvDk3jf0s6wIwxuw7hmDz_wuzRs0dQ',
    appId: '1:91192132276:ios:dfba7544079a1ea1678de1',
    messagingSenderId: '91192132276',
    projectId: 'nlp-chat-app-1fd03',
    storageBucket: 'nlp-chat-app-1fd03.appspot.com',
    iosBundleId: 'com.example.RunnerTests',
  );
}
